version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: semantic-search-api
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
    restart: unless-stopped
    networks:
      - semantic-search-network

  nginx:
    image: nginx:1.25-alpine
    container_name: semantic-search-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - semantic-search-network

networks:
  semantic-search-network:
    driver: bridge
